name: Test & Codecov

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'jest/**'
      - 'jest.json'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      MANGADEX_USERNAME: ${{ secrets.MANGADEX_USERNAME }}
      MANGADEX_PASSWORD: ${{ secrets.MANGADEX_PASSWORD }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1

      - name: set up node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies 🔧
        run: yarn

      - name: Running tests 🚀
        run: yarn run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}